name: AusiriusReplay
version: 1.6.4
main: me.jumper251.replay.ReplaySystem
authors: [Jumper251, iFlamingoz]
depend: [ProtocolLib]
commands:
  replay:
    description: Views the replay GUI
    aliases: [rp, replays]